### ISSUE TITLE
como M... hago tengo ese problema

### ISSUE THREAD

**Issue by jazei-AR** [facuzeta/Personal-Wifi-Zone#1]
hola los 2 botones del wifi estan desactivados. la clave que figura en la etiqueta del equipo no corresp. las cambio telecom supongo
que m.. hago?
no se hacer todo eso tecnico que explicas.
 gracias

**Comment by facuzeta** [comment]
A que clave te referis? Para loguearte en el admin del router/modem? Si es asi, por ahi haciendo un reset de fabrica del equipo se ponga la que es por default, pero no se si eso no te puede dejar sin servicio. Probaste llamando por telefono o por twitter a fibertel a ver si te lo dan de baja del Persona wifi zone?

**Comment by jazei-AR** [comment]
ya consegui la clave que corresp. a mi router, gracias a un redditurro que me permitio abrir este mundo.
te pregunto: Puedo cambiar la clave de logueo del wifi? o lo debe hacer fibertel y no yo? por ahora esta con lista blanca de mac que voy agregando pero me gustaria reforzar cambiando la clave del wifi desde el router...
debo pedirselo a fibertel o lo puedo cambiar yo?
supongo que al apagar el router vuelve todo a 0 ....
muchas gracias,nno tengo a quien mas preguntar, asi que mil disculpas.

**Comment by jazei-AR** [comment]
agrego como lo resolvi:
lo postee aca: https://safereddit.com/r/ArgentinaBenderStyle/comments/17rzbjw/alguna_ayuda_para_desactivar_personal_wifi_zone/
vi un video en el que explicaba como apagar personal wifizone y lo hice y funciona desaparecio del listado de redes disponibles, este es el video: https://vid.puffyan.us/search?q=personal+wifi+zone 
lo de tu explicación para apagar la red parasita  no lo se hacer, no tengo phyton, apenas vim que sí uso pero lo otro no lo se... eso del diccionario ni idea. pero me gustaria lograrlo, saber el listado de redes y eliminar la 9
vi tambien que se puede hacer un backup de la configuración del router.... si sabes algo avisame porfavor, asi cuando se apague el router lo pego dde la copia.
No te molesto mas, no quiero ser abusivo.
Saludos
